-- MySQL Script generated by MySQL Workbench
-- mié 19 ene 2022 10:05:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lpti-ets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lpti-ets` ;

-- -----------------------------------------------------
-- Schema lpti-ets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lpti-ets` ;
USE `lpti-ets` ;

-- -----------------------------------------------------
-- Table `lpti-ets`.`Zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Zona` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Zona` (
  `idZona` INT NOT NULL AUTO_INCREMENT,
  `nomZona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `nomSucursal` VARCHAR(45) NOT NULL,
  `idZona` INT NOT NULL,
  PRIMARY KEY (`idSucursal`, `idZona`),
  INDEX `fk_Sucursal_Zona_idx` (`idZona` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Zona`
    FOREIGN KEY (`idZona`)
    REFERENCES `lpti-ets`.`Zona` (`idZona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Tel_Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Tel_Sucursal` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Tel_Sucursal` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `numTelefono` INT NULL,
  `idSucursal` INT NOT NULL,
  PRIMARY KEY (`idTelefono`, `idSucursal`),
  INDEX `fk_Tel_Sucursal_Sucursal1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Tel_Sucursal_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `lpti-ets`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Personal` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `nomPersonal` VARCHAR(45) NOT NULL,
  `dirPersonal` VARCHAR(45) NOT NULL,
  `celPersonal` VARCHAR(45) NOT NULL,
  `ssPersonal` INT NOT NULL,
  `fnPersonal` VARCHAR(45) NOT NULL,
  `puestoPersonal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`RAdmin_Zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`RAdmin_Zona` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`RAdmin_Zona` (
  `idPersonal` INT NOT NULL,
  `idZona` INT NOT NULL,
  PRIMARY KEY (`idPersonal`, `idZona`),
  INDEX `fk_RAdmin_Zona_Zona1_idx` (`idZona` ASC) VISIBLE,
  CONSTRAINT `fk_RAdmin_Zona_Personal1`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `lpti-ets`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RAdmin_Zona_Zona1`
    FOREIGN KEY (`idZona`)
    REFERENCES `lpti-ets`.`Zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Auto` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Auto` (
  `idAuto` INT NOT NULL AUTO_INCREMENT,
  `marcaAuto` VARCHAR(45) NOT NULL,
  `modAuto` VARCHAR(45) NOT NULL,
  `verAuto` VARCHAR(45) NOT NULL,
  `colAuto` VARCHAR(45) NOT NULL,
  `serAuto` INT NOT NULL,
  `cilAuto` VARCHAR(45) NOT NULL,
  `puerAuto` INT NOT NULL,
  `catAuto` VARCHAR(45) NOT NULL,
  `preAuto` INT NOT NULL,
  PRIMARY KEY (`idAuto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`EMiembro_Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`EMiembro_Sucursal` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`EMiembro_Sucursal` (
  `idPersonal` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  PRIMARY KEY (`idPersonal`, `idSucursal`),
  INDEX `fk_EMiembro_Sucursal_Sucursal1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_EMiembro_Sucursal_Personal1`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `lpti-ets`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMiembro_Sucursal_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `lpti-ets`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fecPedido` VARCHAR(45) NOT NULL,
  `statPedido` VARCHAR(45) NOT NULL,
  `idSucursal` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idSucursal`),
  INDEX `fk_Pedido_Sucursal1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `lpti-ets`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`R_Auto_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`R_Auto_Pedido` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`R_Auto_Pedido` (
  `idPedido` INT NOT NULL,
  `idAuto` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idAuto`),
  INDEX `fk_R_Auto_Pedido_Auto1_idx` (`idAuto` ASC) VISIBLE,
  CONSTRAINT `fk_R_Auto_Pedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `lpti-ets`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_R_Auto_Pedido_Auto1`
    FOREIGN KEY (`idAuto`)
    REFERENCES `lpti-ets`.`Auto` (`idAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpti-ets`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpti-ets`.`Factura` ;

CREATE TABLE IF NOT EXISTS `lpti-ets`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecFactura` VARCHAR(45) NOT NULL,
  `nomCliente` VARCHAR(45) NOT NULL,
  `rfcCliente` VARCHAR(45) NOT NULL,
  `telCliente` VARCHAR(45) NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Sucursal_idZona` INT NOT NULL,
  PRIMARY KEY (`idFactura`, `Sucursal_idSucursal`, `Sucursal_idZona`),
  INDEX `fk_Factura_Sucursal1_idx` (`Sucursal_idSucursal` ASC, `Sucursal_idZona` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_idZona`)
    REFERENCES `lpti-ets`.`Sucursal` (`idSucursal` , `idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
